### Get all blogs
GET http://localhost:3003/api/blogs

### Create a new blog
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IktpbmdFbGlUaGVCb3NzIiwiaWQiOiI2NzhkMzI3ZTBkZjEyYWIxZjdkNTBjNGYiLCJpYXQiOjE3MzczMjgyMTEsImV4cCI6MTczNzMzMTgxMX0.ZBqAasRJqgq8m2wte6WWCwEydDBZC-H-0QZE7326pr0

{
    "title": "Test title",
    "author": "Test author",
    "url": "http://www.youtube.com/",
    "likes": 27
}

### Delete an existing blog
DELETE http://localhost:3003/api/blogs/678d907664c209be24ee2a56
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IktpbmdFbGlUaGVCb3NzIiwiaWQiOiI2NzhkMzI3ZTBkZjEyYWIxZjdkNTBjNGYiLCJpYXQiOjE3MzczMjgyMTEsImV4cCI6MTczNzMzMTgxMX0.ZBqAasRJqgq8m2wte6WWCwEydDBZC-H-0QZE7326pr0